google OAuth를 이용한 회원가입, 로그인 및 토큰 생성 후 응답에 반환 기능 구현
KTPT/surmoon-plz-server pull request #14
Opened 2021-03-18 12:25 UTC by toneyparky

resolve: #10 

현재 메인페이지에서 google 로그인 하이퍼링크를 누르면 구글 로그인으로 이동합니다. 
그 뒤에 로그인 과정이 성공하면 redirect로 설정해둔 login-success로 이동하는데 추후에는 응답 값만 전달하도록 수정해야겠지요.
우선 이 과정이 진행되면 멤버 정보에 없는 사용자는 생성, 있는 사용자는 갱신의 과정을 거치고 그 정보를 바탕으로 JWT 토큰을 생성하여 응답의 body에 넣어주게 됩니다. 

추후에 요청의 헤더로 들어온 토큰 정보를 추출할 때를 대비하여 `TokenExtractor`를 미리 구현해두었습니다.

부족한 부분이 있지만 다음 단계를 진행하려면 기능이 필요할거 같아서 우선 pr 보냅니다.

감사합니다.

2021-03-22 11:32 UTC, kouz95 requested changes
고생하셨습니다. OAuth 생각보다 복잡하군요.

추가적으로 패키지 구조에 대해서 제안하나 드려요. 꼭 이렇게 해야한다가 아니고 이렇게하면 어떨까? 정도이니 의견 부탁드리겠습니다 🙏

![Screen Shot 2021-03-22 at 8 31 22 PM](https://user-images.githubusercontent.com/52931057/111983530-92688c80-8b4d-11eb-965a-4959baa17620.png)

2021-03-22 11:32 UTC, kouz95 commented on survey-service/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
jwt 말고는 클라이언트와 연결되면서 사라질것 같네요. 주석 하나 달아둬도 괜찮을것 같아요.

2021-03-22 11:32 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/config/SecurityConfig.java
> +            .antMatchers("/login-success").authenticated()
anyRequest에 `/login-success` 도 잡힐 것 같은데 맞나요?

2021-03-22 11:32 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/oauth/token/TokenExtractor.java
> +public class TokenExtractor {
현재는 사용되지 않는 것 같은데 이후 Token이 담긴 요청이 올때 사용하는 건가요?

2021-03-23 06:15 UTC, Jummi10 reviewed
수고하셨습니다!! 👍

2021-03-23 06:15 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/oauth/OAuth2MemberService.java
> +    }
기존에 존재하는 member가 로그인을 하면 매번 rename()을 해주는 것인가요? 만약에 그렇다면 그럴 필요가 있는것인지, 다른 이유가 있는 것인지 궁금합니다!

2021-03-23 06:15 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/oauth/token/TokenExtractor.java
> +public class TokenExtractor {
> 추후에 요청의 헤더로 들어온 토큰 정보를 추출할 때를 대비하여 `TokenExtractor`를 미리 구현해두었습니다.

승완님께서 [코멘트](https://github.com/KTPT/surmoon-plz-server/pull/14#issue-595505951)로 이렇게 달아놓으셨네요! 😎

2021-03-23 07:01 UTC, toneyparky commented on survey-service/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
오 좋습니다. 반영해서 처리했어용~

2021-03-23 07:05 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/config/SecurityConfig.java
> +            .antMatchers("/login-success").authenticated()
`login-success`를 명시해주고 싶었는데 생각해보니 아래에 명시가 되어있으니 17번째 줄은 제거되어도 괜찮다 싶네요!
~~~java
            .defaultSuccessUrl("/login-success", true);
~~~

좋습니다~

2021-03-23 07:06 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/oauth/token/TokenExtractor.java
> +public class TokenExtractor {
정미님 답변 감사합니다~

2021-03-23 07:23 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/oauth/OAuth2MemberService.java
> +    }
`Member`를 생성할 때에 `OAuth2UserInfo`에 있는 정보 중 email을 유니크 값이라고 상정하고 생성합니다.
위의 37번째 줄에서 email로 조회를 하는걸 보면 알 수 있죵.

`OAuth2UserInfo`에 있는 email은 바뀌지 않지만 name은 바뀔 수 있다고 생각해서 name에 대해 수정된 사항을 계속 갱신할 수 있도록 처리를 해줬어요!

저희가 직접 사용자 정보를 입력받지(닉네임이라든가..,) 않기 때문에 구글계정에서 이름을 변경했을 때 변경된 내용이 반영되길 바라는 마음에서 매번 rename을 해주네요. 단순히 rename이 아니라 같지 않을 경우에만 rename이 되도록 수정하는 방향이 좋을 것 같습니다! 
좋은 포인트에요😀

2021-03-23 07:25 UTC, toneyparky commented
@kouz95 패키지 관련해서 조언주신 부분에 대해서 질문이 있습니다!
adaptor와 infra라는 디렉토리에 담겨있는 의미가 있을까요?
adaptor안에 들어간다는 부분과 바로 oauth로 관리하는 부분에 대한 차이가 궁금합니다!

2021-03-23 07:36 UTC, kouz95 commented
> @kouz95 패키지 관련해서 조언주신 부분에 대해서 질문이 있습니다!
> 
> adaptor와 infra라는 디렉토리에 담겨있는 의미가 있을까요?
> 
> adaptor안에 들어간다는 부분과 바로 oauth로 관리하는 부분에 대한 차이가 궁금합니다!

사실 제가 텍스트로 설명드리는 것보다 영상을 참고하시는게 훨씬 이해하기가 쉬울 것 같아요.

[DDD Lite](https://youtu.be/TdyOH1xZpT8)

_34분 40초부터 나옵니다_


무조건 이렇게 만들어야 한다라고 생각하지는 않습니다.
다만 이런 패키지 구조를 해보면서 느낀것은, 요청과 응답의 과정이 좀 더 명확하게 느껴졌다는 것과 자연스레 도메인으로 집중 시킬수 있었다는 점이 있었습니다. 🙂

2021-03-24 10:57 UTC, toneyparky commented
@kouz95 

첨부해주신 영상 정말 재미있게 잘 봤어요 좋네요 
경쥰쨩이 사용했던 개념들이 다 들어있네요 👍


그리고 말씀해주신 
> 또한 제안드린 방법도 부족한 것이, spring oauth가 아닌 다른 기술을 통한 oauth를 사용할 가능성도 열어, 도메인이나 어플리케이션 레이어에 인터페이스를 두고 인프라엔 spring oauth라고 해야 이러한 아키텍처의 장점을 얻게 된다고도 생각합니다.
하지만 오버이긴 하죠..

에 대해서도 영상 후반부의 `헥타곤 아키텍쳐에서 도메인으로 의존 방향을 둬라`는 부분에 대한 코멘트로 생각 되어지네용.

현재로서는 조금 오버라는데에도 동의하기에 제안해주신 패키지 구성을 반영하는 정도로 이번 pr 마무리하겠습니다!

항상 좋은 인사이트 때땡큐

2021-03-24 11:18 UTC, merged