Section API 구현
KTPT/surmoon-plz-server pull request #15
Opened 2021-03-21 16:07 UTC by Jummi10

resolve #13 

생각보다 만만치 않아서 더 재밌게 한 것 같습니다 ㅎ 로직 잘못된 부분이 있거나 허술한 부분 있으면 마구 지적해주세요!

2021-03-22 12:30 UTC, kouz95 requested changes
고생하셨습니다. 잘하셨네요.
리뷰 확인해주세요 🙂

2021-03-22 12:30 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +    public Section insertSequence(SectionRequest request) {
도메인 서비스가 어플리케이션 레이어에있는 SectionRequest를 의존하는건 좋지 않은것 같아요.
SectionRequest가 아니어도 새로 들어올 section과 surveyId만 알고 있으면 insertSequence 기능을 사용할 수 있도록 만들수 있지 않을까요?

2021-03-22 12:30 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
previousSectionId를 -1로 넣어주는 이유는 무엇인가요?

2021-03-22 12:30 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
-1을 상수화에서 의미를 담아주어도 좋을것 같아요

2021-03-22 12:30 UTC, kouz95 commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/IntegrationTest.java
> +                    MockMvcResultMatchers.header().string(HttpHeaders.LOCATION, Matchers.matchesRegex(uri + "/\\d*")))
뭔가 들여쓰기 설정이 일치하지 않는것 같아요. 변경된 것은 없는데 files changed로 잡히네요.
다음에 모였을때 IDE설정을 통일 시키는게 좋을것 같아요 🙂

2021-03-22 12:30 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/SectionService.java
> +        Section section = sectionSequenceService.insertSequence(request);
insertSequence한 결과로 나온 section이 어떤 section인가요? 변수명으로 표현해주시면 좋을것 같습니다.

2021-03-23 06:43 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +    public Section insertSequence(SectionRequest request) {
section을 새로 생성하는 과정도 insertSequence()에서 하려다보니 request를 다 넘겨주게 되었는데
 `SectionService.save()`에서 section을 생성하고 그걸 넘겨주면 되겠네요!

2021-03-23 06:44 UTC, Jummi10 commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/IntegrationTest.java
> +                    MockMvcResultMatchers.header().string(HttpHeaders.LOCATION, Matchers.matchesRegex(uri + "/\\d*")))
앗 저번에 다 맞춘줄 알았는데 또 이렇게 맞지 않는군요ㅠ

2021-03-23 07:04 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
1. 의미 없는 previousSectionId=-1을 가진 새로운 section A 생성
- `2.`에서 section A의 id가 필요하기 때문에 먼저 생성해줌
2. request.previousSectionId를 가진 기존의 section B를 찾아서 B.previousSectionId = A.id로 교체
- `1.`에서 A에 prviousSectionId = -1로 넣어주지 않으면 `sectionRepository.findOptionalByPreviousSectionId(request.getPreviousSectionId())`에서 동일한 previousSectionId를 가진 section이 두 개가 찾아지기 때문
3. A.previousSectionId = request.previousSectionId 로 수정, A 생성 완료
이 과정으로 새로운 섹션이 만들어지기 때문에 previousSectionId를 -1로 넣어주는 것입니다

2021-03-23 08:05 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
음.. 더 쉬운 과정은 없을까 고민이 되네요. 섹션을 추가하는 것 만으로 DB를 4번 찔러야 하나 라는 생각도 있고..

만약에 동일한 previousSectionId를 가진 section이 두 개가 찾아 진다면, 이전에 생성된 섹션을 새로 만든 섹션의 아이디로 업데이트 한다 라고 하면 쿼리 한번은 줄일 수 있지 않을까요?

2021-03-23 08:05 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
만약 필요한게 새로 생성될 섹션의 아이디라면, 섹션을 조회하는게 아니라 hibernate sequence를 바로 조회하는 방법이 있진 않을까 하는 생각도 있어요.

2021-03-23 08:31 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
흠 사실 저도 구현하면서 이렇게 복잡하게 해야하나라는 생각이 들긴 했었는데 pr 코멘트를 남기며 여러분들께 물어본다는 것을 잊어먹었네요!

> 만약 필요한게 새로 생성될 섹션의 아이디라면, 섹션을 조회하는게 아니라 hibernate sequence를 바로 조회하는 방법이 있진 않을까 하는 생각도 있어요.

Section의 id를 `@GeneratedValue(strategy=GenerationType.SEQUENCE)`로 설정해서 사용하자는 말씀이신가요??

2021-03-23 08:47 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
[하이버네이트는 어떻게 자동 키 생성 전략을 결정하는가](https://www.popit.kr/%ED%95%98%EC%9D%B4%EB%B2%84%EB%84%A4%EC%9D%B4%ED%8A%B8%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%9E%90%EB%8F%99-%ED%82%A4-%EC%83%9D%EC%84%B1-%EC%A0%84%EB%9E%B5%EC%9D%84-%EA%B2%B0%EC%A0%95%ED%95%98/)

위 글은 '어떻게 전략을 결정하는지' 에 대한 글이고 hibernate sequence table을 사용하는 법에 대해 다루진 않았습니다만, 아이디가 1씩 올라가는 것이 어떤식으로 동작하는지 설명이 될것 같아 첨부 드립니다.

hibernate sequence에 의해서 관리가 되니 이걸 활용하면 다음으로 부여될 아이디를 알 수 있지 않을까라는 생각이 들어서 말씀 드렸던 부분입니다.

2021-03-24 12:56 UTC, toneyparky requested changes
리뷰 남겼습니당~
어려운 부분을 잘 구현해주셨네요🙂

생각해볼 부분을 남겼으니 이야기 나눠보죠!

2021-03-24 12:56 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +            throw new IllegalArgumentException("해당 survey가 아닙니다, surveyId : " + surveyId);
아래처럼 에러 메시지를 조금 더 명확히 해줘도 좋을 것 같아용

```suggestion
            throw new IllegalArgumentException("수정할 survey와 동일하지 않습니다, 수정할 surveyId: " + this.surveyId + "입력 받은 surveyId : " + surveyId);
```

2021-03-24 12:56 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +    }
현재 로직을 따른다면 title만 바꾸거나 description만 바꾼 경우에 예외가 발생할 거 같습니다.
특히 자동 저장을 사용할 경우 title이나 description만 바뀐 상태에서 자동으로 업데이트 api를 쏠 경우도 빈번할 거 같아서 유효성 검사를 OR 조건으로 연결해줘도 좋을 것 같네용

칭구들의 의견이 궁금합니당 어떻게 생각하시는가요?

2021-03-24 12:56 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/adapter/presentation/SectionController.java
> +    @PatchMapping("/{id}/content")
put 보다 patch가 더 적절한 메서드라 생각해용
굳굳~

2021-03-24 12:59 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
hibernate관련 이야기는 실제 DB를 찔러서 생성될 최신 id를 얻는 방법이 아니라 JVM 상의 hibernate에서 id 값을 관리하게 하고 그 값을 얻어와서 DB 통신을 줄이자라는 부분으로 이해했는데 맞나용?

2021-03-24 13:00 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
@toneyparky 명확한 방법은 모르겠으나, id만 얻는 방법이 있지 않을까 정도 였습니다,,

2021-03-24 13:02 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +    }
맞네요. 
다만, OR이 맞나요? AND이지 않나요? (둘다 같을 경우 예외)

2021-03-24 13:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +    }
아아 AND네요 맞슴니당~

2021-03-24 13:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
저도 좀 알아볼게유

2021-03-24 17:36 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +    }
오호 구글폼에서는 description과 title이 한 번에 동시에 수정될 수 없으니 (구글폼의 자동저장되는 방식을 보면 description 칸에서 한 번 수정하자마자 바로 저장이 되고, title도 마찬가지로 수정하면 바로 저장 중이 뜨길래요) 따로 예외 처리를 해준 것이었습니다. 하지만 승완님 말처럼

> 특히 자동 저장을 사용할 경우 title이나 description만 바뀐 상태에서 자동으로 업데이트 api를 쏠 경우

라고 생각하면 AND로 해주는 게 맞는 것 같네요! 수정하겠습니다

2021-03-24 17:37 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +        Section section = sectionRepository.save(request.toEntity(-1L));
이 부분이 제일 어렵네용 `section`뿐만 아니라 `question item`과 `option` 생성 부분에서도 사용될 것 같으니 저도 열심히 찾아보겠습니다~

2021-03-27 15:43 UTC, kouz95 approved these changes
사소한 리뷰 하나 있으니 확인해주세요.

고생하셨습니다 🙂

2021-03-27 15:43 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/SectionSequenceService.java
> +            .ifPresent(it -> it.updatePreviousSectionId(created.getId(), surveyId));
👍

2021-03-27 15:43 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/section/Section.java
> +            throw new IllegalArgumentException("동일한 title 혹은 description으로 변경할 수 없습니다.");
메세지는 or를 의미하긴 하는것 같아요
```suggestion
            throw new IllegalArgumentException("동일한 title 과 description으로 변경할 수 없습니다.");
```

2021-03-28 03:53 UTC, toneyparky approved these changes
수고하셨습니다~

컨플릭트나는 부분만 반영해서 커밋하시면 바로 머지할게용~

2021-03-28 12:21 UTC, merged