설문 API
KTPT/surmoon-plz-server pull request #4
Opened 2021-03-08 17:57 UTC by kouz95

2021-03-08 18:08 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/adapter/presentation/SurveyController.java
> +     * @param request's title, creatorId will be verified by domain (NO @Valid)
update의 경우 @NotBlank, @MemberShouldExist로 검사 되는것이 아닌, domain의 update 메소드에서 검사하도록 구현하였습니다.

- 혼동을 방지하기위해 SurveyCreateRequest와, SurveyUpdateRequest를 나누어야 할까요?

2021-03-08 18:11 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyRequest.java
> +    // TODO: 2021/03/09 can be blank?
제목 수정의 경우 공백으로 수정이 가능할 것도 같습니다. (CreateRequest와 UpdateRequest가 분리되어야 할까요?)
- 최초 생성시엔 공백이 아닌 상태로 들어와야한다. (client가 title이 적힌 이후 요청)
- 유저가 title을 비웠을때 요청이 날라와야한다.

2021-03-08 18:11 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyRequest.java
> +    // TODO: 2021/03/09 extracted by header (token)
회원 인증/인가 방식을 토큰으로 하는순간 사라지게 됩니다.

2021-03-08 18:12 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +    // TODO: 2021/03/09 공동 편집자?
공동 편집 기능이 생긴다면, 영향을 받을 부분이라고 생각했습니다.

2021-03-08 18:57 UTC, hwookim commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +    }
동시성 문제가 있진 않을까요.

`A->Aa` 의 요청과 그 뒤 곧바로 `Aa->A`의 요청이 들어왔을 때,
선행 요청이 DB에 저장되기 전에 후행 요청의 조회가 발생해버렸다면 오류가 발생하겠네요.

물론 동시성 문제는 어디서나 발생하겠지만....
그냥 갑자기 생각이 났어요...

2021-03-08 18:58 UTC, hwookim commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
동시성 문제가 있진 않을까요.

`A->Aa` 의 요청과 그 뒤 곧바로 `Aa->A`의 요청이 들어왔을 때,
선행 요청이 DB에 저장되기 전에 후행 요청의 조회가 발생해버렸다면 오류가 발생하겠네요.

물론 동시성 문제는 어디서나 발생하겠지만....
그냥 갑자기 생각이 났어요...

2021-03-08 19:05 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
낙관적 잠금에 관련된 오류라고 생각되네요.
두 명 이상의 유저가 수정하는것을 허용하여 동시성 문제가 생기게 된다면 소켓으로 해결해야될 것 같고,

그게 아니라면 client에서 response를 받은 후에 요청을 보내야 한다가 되어야 할 것 같아요.

client가 보장을 안해준다면 버전을 추가하여 낙관적 잠금을 적용해야 될 것 같네요.

https://reiphiel.tistory.com/m/entry/understanding-jpa-lock

2021-03-08 19:07 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
만약 낙관적 잠금을 적용하고, client는 응답을 받지 않은채로 요청을 보낸다로 가게 된다면 아마도 무수한 400을 받게 되실거에요 ㅎㅎ..

2021-03-09 00:03 UTC, toneyparky requested changes
너무나 깔끔. 테스트 관련 분리도 흠 잡을 데 없음. 역시 멋쟁이.

1. `SurveyUpdateRequest` 분리 이슈
  분리 안해도 괜찮다는 의견

2. 현우가 제시한 동시성 문제
  우선은 지금대로 진행하고 실제로 테스트를 해보자는 의견

3. AdviceController에서 예기치 못한 오류를 잡을 수 있는 메서드를 추가하자는 제안

4. 제목 수정, 혹은 생성시 공백 허용에 관한 로직
  도메인에서 공백 불가로 막아놓고 프론트에서도 구글 폼즈의 로직을 따라서 정상적으로 요청을 보낼 경우에는 무조건 채워서 보낼 수 있도록 처리

5. 회원 기능이 우선순위가 높다
  동의. 회원 기능을 어찌 구현할지 (OAuth, Local 등)에 대한 논의 필요 => 이슈에 띄우겠음

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/adapter/presentation/SurveyController.java
> +     * @param request's title, creatorId will be verified by domain (NO @Valid)
수정할 경우 request의 검증은 Survey가 하는게 타당하다는 논리로 `@Valid`를 안해준걸로 이해하면 될까요?
그렇다면 자바독으로 명시해두었으니 분리하지 않아도 괜찮을거 같습니다😊

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/adapter/presentation/advice/ExceptionController.java
> +}
마지막에 `Exception`을 받아서 처리하는 메서드를 하나 넣어주죠!

지금 존재하는 두 메서드에서 안걸리는 예외에 대해서도 걸러서 `ExceptionController`에서 처리해주기 위함입니다.

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyRequest.java
> +    // TODO: 2021/03/09 extracted by header (token)
맞습니다.

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyRequest.java
> +    // TODO: 2021/03/09 can be blank?
검증은 해주되 프론트에서 공백일 경우에 디폴트로 Survey title을 넣어줘도 좋을 것 같다는 생각이 드네요.
공백값이 들어오지 않도록요.
실제 구글 폼즈에서도 이렇게 처리가 되는 것 같습니다. 모든 정상적인 요청에 대해서 title이 비어 있을 수 없도록요.

제가 발견한 로직을 말해볼게요 
- 초기 생성시 섹션1의 타이틀과 survey의 타이틀 모두 제목 없는 설문지이다.
- 섹션1의 타이틀을 바꾸어도 survey 타이틀은 그대로다.
  -  수정되었던 섹션1의 타이틀을 공백으로 만들면 survey의 타이틀이 입력된다.
- survey 타이틀을 바꾸면 섹션1의 타이틀도 수정된다.
  - survey의 타이틀이 수정된 상황에서 섹션1의 타이틀을 공백으로 만들면 survey의 타이틀이 입력된다.
  - 수정되었던 survey 타이틀을 공백으로 만들면 survey의 타이틀과 섹션의 title 모두 제목 없는 설문지로 바뀐다.

![image](https://user-images.githubusercontent.com/37579660/110395004-ba1d1680-80b0-11eb-861d-e963d2619c9d.png)
![image](https://user-images.githubusercontent.com/37579660/110395384-5e06c200-80b1-11eb-8462-89d81cfbf042.png)

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyResponse.java
> +    private final LocalDateTime lastModifiedDate;
CQRS를 적용할 예정이기에 이 친구가 사용자 조회시 그대로 반환되는건 아니라는 생각이 드는데 제가 의도를 잘 파악했나요?

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/validation/MemberExistVerifier.java
> +public class MemberExistVerifier implements ConstraintValidator<MemberShouldExist, Long> {
`ConstraintValidator ` 재미있는 친구네요.
`MemberShouldExist`어노테이션이 검증해야 하는 로직을 담고 있군요!! 배워갑니다~

일전에는 해당 어노테이션 여부를 확인하는 필터나 인터셉터를 작성했던거 같은데 이렇게 처리하면 되는군요. 
내부적인 원리는 차차 알아봐야겠슴다😬

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +    // TODO: 2021/03/09 공동 편집자?
머나먼 미래에 추가될 기능처럼 느껴지지만 공동 편집자가 생긴다면 테이블을 따로 빼야겠군용

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
제안해주신 이슈를 고려하면서 구현해보고 확인해보죠!

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/SurveyIntegrationTest.java
> +        // when
공백이 들어가면 위의 메서드들과 컨벤션이 맞을거 같아용~

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/SurveyIntegrationTest.java
> +                () -> assertThat(response.getLastModifiedDate().isAfter(saved.getLastModifiedDate())).isTrue()
좋네요!

2021-03-09 00:03 UTC, toneyparky commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/SurveyIntegrationTest.java
> +                    assertThat(response.getMessages()).containsExactly("같은 내용으로 수정할 수 없습니다.");
```suggestion
                    assertThat(response.getMessages()).containsExactly("같은 title로 수정할 수 없습니다.");
```

현재 `Survey` 내부에서 해당 검증에 대한 내용은 `title`만 확인하기에 요게 더 명확할 거 같습니다.

~~~java
        // Survey
        if (this.title.equals(title)) {
            throw new IllegalArgumentException("같은 내용으로 수정할 수 없습니다.");
        }
~~~

2021-03-09 00:25 UTC, hwookim commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
만일 낙관적 잠금을 이용한다면, 버전이 달라 오류가 발생했을 때 해당 요청을 서버 내에서 다시 실행하는 것으로 어느정도 400의 반환을 경감할 수 있을거라 생각해요.

그 전에 `title이 같은 경우가 오류인가?` 라는 생각도 드네요.
물론 불필요한 DB 접속이 일어날 여지는 있겠습니다만... 위에서 제가 말한 경우에는 그냥 마지막 저장만 잘 일어났으면 아무 문제도 없지 않은가 싶어요.

2021-03-09 05:36 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/validation/MemberExistVerifier.java
> +public class MemberExistVerifier implements ConstraintValidator<MemberShouldExist, Long> {
이전에는 PathVariable을 수평적으로 처리하려다보니 AOP로 해결하게 되었습니다.
body로 들어오는것은 spring validation을 활용하여 처리할 수 있었습니다.

https://cheese10yun.github.io/spring-custom-valdate-annotation/

2021-03-09 05:37 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyResponse.java
> +    private final LocalDateTime lastModifiedDate;
조회용 응답보단, client가 요청을 성공한 이후에 받게되는 응답입니다.

2021-03-09 05:40 UTC, kouz95 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
이 문제는 한번 지켜보죠. 실제 유즈케이스에서 어떨지 봐야겠네요.

2021-03-09 07:54 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/SurveyResponse.java
> +    private final LocalDateTime lastModifiedDate;
좋습니당
이해했고 동의합니다.

location만 보내주기보다는 객체도 같이 보내주면 좋죠~

2021-03-09 07:56 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/application/dto/validation/MemberExistVerifier.java
> +public class MemberExistVerifier implements ConstraintValidator<MemberShouldExist, Long> {
이해하기 쉽도록 예시까지!
최고😎

2021-03-09 18:17 UTC, Jummi10 reviewed
활발한 토론이 이루어졌군요! 다들 이미 많은 코멘트를 달아주셔서 코드와 리뷰 공부하면서 재미있게 봤습니다..! 수고하셨습니다 :-)

2021-03-09 18:17 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        this.title = title;
`whoCreator`의 의미가 creator이냐 검증하는 의미인가요? 기능 자체로만 보자면 survey의 title을 업데이트하는 의미가 더 크지 않나요!

2021-03-09 18:17 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +    // TODO: 2021/03/09 공동 편집자?
@kouz95 멀리까지 내다보고 계시는군요

2021-03-09 18:17 UTC, Jummi10 commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
title의 변경 사항이 없는데도 update 요청이 들어오나요?? 이 부분은 프론트에서가 아니라 이곳에서 처리해야 하는 부분인가요!

2021-03-09 18:17 UTC, Jummi10 commented on survey-service/src/test/java/com/ktpt/surmoon/service/survey/integration/SurveyIntegrationTest.java
> +                () -> assertThat(response.getLastModifiedDate().isAfter(saved.getLastModifiedDate())).isTrue()
오 Quna에서는 `isNotEqualTo`를 썼었던것 같은데 `isAfter`가 훨 좋은 것 같네요!!

2021-03-10 08:32 UTC, toneyparky commented on survey-service/src/main/java/com/ktpt/surmoon/service/survey/domain/model/survey/Survey.java
> +        }
중복 검증이라고 생각했습니다!

2021-03-10 08:33 UTC, toneyparky commented
가볍게 이야기 나누고 머지를 시키죠~!

2021-03-10 13:59 UTC, kouz95 commented
- ControllerAdvice에 RuntimeException을 추가했습니다. 
- Survey.updateWhoCreator -> Survey.changeTitleWhoCreator로 변경하였습니다.
- 설문 업데이트 요청에도 `@Valid`를 사용하였습니다. (업데이트 요청시에도 title은 공백일 수 없다.)

2021-03-10 22:47 UTC, toneyparky approved these changes
수고해씀~
머지 할게~

2021-03-10 22:48 UTC, merged